"""empty message

Revision ID: 212ba20414c2
Revises: 6c5ac7557953
Create Date: 2023-12-21 10:07:12.899037

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '212ba20414c2'
down_revision = '6c5ac7557953'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('answer', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text("'1'"))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('answer', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text("'1'"))

    # ### end Alembic commands ###
