"""empty message

Revision ID: 343cdefff7c9
Revises: 3a7e0a76c744
Create Date: 2023-12-21 10:04:58.607231

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '343cdefff7c9'
down_revision = '3a7e0a76c744'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
